//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream backMusic {
            get {
                return ResourceManager.GetStream("backMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ball {
            get {
                object obj = ResourceManager.GetObject("ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blueBrick {
            get {
                object obj = ResourceManager.GetObject("blueBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blueBrick2 {
            get {
                object obj = ResourceManager.GetObject("blueBrick2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream brickCollision {
            get {
                return ResourceManager.GetStream("brickCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream collision {
            get {
                return ResourceManager.GetStream("collision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream deathSound {
            get {
                return ResourceManager.GetStream("deathSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Green_Brick {
            get {
                object obj = ResourceManager.GetObject("Green_Brick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greenBrick2 {
            get {
                object obj = ResourceManager.GetObject("greenBrick2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level number =&quot;1&quot; name =&quot;Level 1&quot;&gt;
        ///  &lt;brick x =&quot;50&quot; y =&quot;47&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x=&quot;125&quot; y=&quot;47&quot; hp=&quot;1&quot;/&gt;
        ///  &lt;brick  x=&quot;50&quot; y=&quot;90&quot; hp=&quot;1&quot;/&gt;
        ///  &lt;brick  x=&quot;125&quot; y=&quot;90&quot; hp=&quot;1&quot;/&gt;
        ///  &lt;brick  x=&quot;50&quot; y=&quot;137&quot; hp=&quot;2&quot;/&gt;
        ///  &lt;brick  x=&quot;125&quot; y=&quot;137&quot; hp=&quot;2&quot;/&gt;
        ///  &lt;brick x=&quot;530&quot; y=&quot;47&quot; hp=&quot;1&quot;/&gt;
        ///  &lt;brick x=&quot;608&quot; y=&quot;47&quot; hp=&quot;1&quot;/&gt;
        ///  &lt;brick x=&quot;530&quot; y=&quot;90&quot; hp=&quot;1&quot;/&gt;
        ///  &lt;brick x=&quot;608&quot; y=&quot;90&quot; hp=&quot;1&quot;/&gt;
        ///  &lt;brick x=&quot;530&quot; y=&quot;137&quot; hp=&quot;2&quot;/&gt;
        ///  &lt;brick x=&quot;608&quot; y=&quot;137&quot; hp=&quot;2&quot;/&gt;
        ///  &lt;brick x=&quot;302&quot; y= [rest of st....
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level number=&quot;2&quot; name=&quot;5 x 2 = 10E&quot;&gt;
        ///  &lt;brick x =&quot;266&quot; y =&quot;365&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;340&quot; y =&quot;365&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;413&quot; y =&quot;365&quot; hp =&quot;1&quot;/&gt;
        ///
        ///  &lt;brick x =&quot;266&quot; y =&quot;317&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;340&quot; y =&quot;317&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;413&quot; y =&quot;317&quot; hp =&quot;1&quot;/&gt;
        ///
        ///  &lt;brick x =&quot;266&quot; y =&quot;268&quot; hp =&quot;2&quot;/&gt;
        ///  &lt;brick x =&quot;340&quot; y =&quot;268&quot; hp =&quot;2&quot;/&gt;
        ///  &lt;brick x =&quot;413&quot; y =&quot;268&quot; hp =&quot;2&quot;/&gt;
        ///
        ///  &lt;brick x =&quot;266&quot; y =&quot;217&quot; hp =&quot;2&quot;/&gt;
        ///  &lt;brick x =&quot;340&quot; y =&quot;217&quot; hp =&quot;2&quot;/&gt;
        ///  &lt;brick  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;level number =&quot;3&quot; name =&quot;This is Jimmy&quot;&gt;
        ///  &lt;brick x =&quot;0&quot; y =&quot;200&quot; hp =&quot;4&quot;/&gt;
        ///  &lt;brick x =&quot;93&quot; y =&quot;200&quot; hp =&quot;4&quot;/&gt;
        ///  &lt;brick x =&quot;186&quot; y =&quot;200&quot; hp =&quot;4&quot;/&gt;
        ///  &lt;brick x =&quot;279&quot; y =&quot;200&quot; hp =&quot;4&quot;/&gt;
        ///  &lt;brick x =&quot;372&quot; y =&quot;200&quot; hp =&quot;4&quot;/&gt;
        ///  &lt;brick x =&quot;465&quot; y =&quot;200&quot; hp =&quot;4&quot;/&gt;
        ///  &lt;brick x =&quot;558&quot; y =&quot;200&quot; hp =&quot;4&quot;/&gt;
        ///  &lt;brick x =&quot;651&quot; y =&quot;200&quot; hp =&quot;4&quot;/&gt;
        ///
        ///  &lt;brick x =&quot;0&quot; y =&quot;147&quot; hp =&quot;2&quot;/&gt;
        ///  &lt;brick x =&quot;93&quot; y =&quot;147&quot; hp =&quot;2&quot;/&gt;
        ///  &lt;brick x =&quot;186&quot; y =&quot;147&quot; hp =&quot;2&quot;/&gt;
        ///  &lt;brick x =&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level number =&quot;4&quot; name =&quot;You are not Thayen&quot;&gt;
        ///  &lt;brick x =&quot;223&quot; y =&quot;193&quot; hp =&quot;3&quot;/&gt;
        ///  &lt;brick x =&quot;279&quot; y =&quot;193&quot; hp =&quot;3&quot;/&gt;
        ///  &lt;brick x =&quot;335&quot; y =&quot;193&quot; hp =&quot;3&quot;/&gt;
        ///  &lt;brick x =&quot;391&quot; y =&quot;193&quot; hp =&quot;3&quot;/&gt;
        ///  &lt;brick x =&quot;447&quot; y =&quot;193&quot; hp =&quot;3&quot;/&gt;
        ///  &lt;brick x =&quot;503&quot; y =&quot;193&quot; hp =&quot;3&quot;/&gt;
        ///
        ///  &lt;brick x =&quot;103&quot; y =&quot;68&quot; hp =&quot;2&quot;/&gt;
        ///  &lt;brick x =&quot;176&quot; y =&quot;68&quot; hp =&quot;2&quot;/&gt;
        ///  &lt;brick x =&quot;36&quot; y =&quot;104&quot; hp =&quot;2&quot;/&gt;
        ///  &lt;brick x =&quot;103&quot; y =&quot;104&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;176&quot; y =&quot;104&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;bric [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level number =&quot;5&quot; name =&quot;This one&quot;&gt;
        ///  &lt;brick x =&quot;12&quot; y =&quot;349&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;68&quot; y =&quot;349&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;124&quot; y =&quot;349&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;12&quot; y =&quot;349&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;180&quot; y =&quot;349&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;236&quot; y =&quot;349&quot; hp =&quot;1&quot;/&gt;
        ///
        ///  &lt;brick x =&quot;523&quot; y =&quot;349&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;579&quot; y =&quot;349&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;635&quot; y =&quot;349&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;691&quot; y =&quot;349&quot; hp =&quot;1&quot;/&gt;
        ///  &lt;brick x =&quot;747&quot; y =&quot;349&quot; hp =&quot;1&quot;/&gt;
        ///
        ///  &lt;brick x =&quot;30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level5 {
            get {
                return ResourceManager.GetString("Level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream lifeLost {
            get {
                return ResourceManager.GetStream("lifeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream paddleCollision {
            get {
                return ResourceManager.GetStream("paddleCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player1 {
            get {
                object obj = ResourceManager.GetObject("Player1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2 {
            get {
                object obj = ResourceManager.GetObject("Player2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Powerup {
            get {
                return ResourceManager.GetStream("Powerup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap purpBrick {
            get {
                object obj = ResourceManager.GetObject("purpBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap purpBrick2 {
            get {
                object obj = ResourceManager.GetObject("purpBrick2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap purpbutton {
            get {
                object obj = ResourceManager.GetObject("purpbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redBrick {
            get {
                object obj = ResourceManager.GetObject("redBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redBrick2 {
            get {
                object obj = ResourceManager.GetObject("redBrick2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stars {
            get {
                object obj = ResourceManager.GetObject("Stars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
